### ISSUE TITLE
建議加上淤積比例

### ISSUE THREAD

**Issue by tooto1985** [chihsuan/reservoir-visual#10]
蓄水量不代表可用水量
最近新聞上有報導淤泥嚴重
建議扣除淤積量才是有效使用量
以上建議，謝謝！

**Comment by chihsuan** [comment]
您好, 目前的蓄水量是指”有效蓄水量“（稍後更改名稱），是指水庫總容量中，能調節提供有效使用水量之部分容量，亦即由總容量中扣除呆容量後之容量。應是有納入淤泥的考量，謝謝。
Ref1: http://wuss.wra.gov.tw/systeminfo.aspx
Ref2: http://www.cerma.org.tw/page84.php
