### ISSUE TITLE
建議加上可用天數

### ISSUE THREAD

**Issue by dca** [chihsuan/reservoir-visual#5]
建議可以考慮加上目前蓄水量的「預估可用天數」

這樣或許能讓大家有更深刻的「再過幾天就沒水用」的感覺

**Comment by johnroyer** [comment]
水利署有個可以查詢用水量的資料庫
http://wuss.wra.gov.tw/

## 

補充：剛剛發現網站上的資料，最新只有民國 101 年，所以可能沒有實際用途

**Comment by chihsuan** [comment]
這裡 washwashsleep 有提供水庫許資料API
[https://github.com/washwashsleep/TaiwanReservoirAPI](https://github.com/washwashsleep/TaiwanReservoirAPI)

直覺來說可能可以單純用“昨日用水量”去預估，但覺得這樣做可能也會有些問題...
所以目前還沒有什麼想到好方法去預估，如果不錯的方法可以討論或PR Thanks : )
